### ISSUE TITLE
Don't collapse agent responses 

### ISSUE THREAD

**Issue by dahifi** [culture-dao/chainlit-template#39]
Right now longer stream responses are collapsed after the complete. We would like to know what can be done to prevent this, whether it's a config option or in source.

**Comment by Lauren1066** [comment]
From Ask Chainlit:

To prevent messages from collapsing in your Chainlit application, you can set the `default_collapse_content` option to false in your UI configuration. This will keep the threads expanded, displaying large text content without automatically collapsing it.

Here's how you can modify the UI configuration to achieve this:

```
[UI]
default_collapse_content = false
```
This option is part of the UI configuration settings that allow you to customize the behavior and appearance of your Chainlit application's user interface.
